services:
  claude:
    build: .
    container_name: claude
    stdin_open: true
    tty: true
    volumes:
      # Mount your project directory here
      - ${WORKSPACE_LOCAL}:${WORKSPACE_DOCKER-/workspace}
      # Optionally mount Claude config
      - ~/.gitconfig:/home/claude/.gitconfig
      - ~/.ssh:/home/claude/.ssh
      - ~/.claude:/home/claude/.claude
      - ~/.claude.json:/home/claude/.claude.json
    working_dir: ${WORKSPACE_DOCKER-/workspace}
